apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  REACT_APP_USERNAME: "apschni"
  REACT_APP_COMPANY_NAME: "bebracorp"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-for-lab3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-for-lab3
  template:
    metadata:
      labels:
        app: frontend-for-lab3
    spec:
      containers:
        - name: frontend-for-lab3
          image: ifilyaninitmo/itdt-contained-frontend:master
          envFrom:
            - configMapRef:
                name: frontend-config
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: lab3-service
spec:
  type: NodePort
  selector:
    app: frontend-for-lab3
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab3-ingress
spec:
  tls:
    - hosts:
        - apschni.com
      secretName: frontend-tls
  rules:
    - host: apschni.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lab3-service 
                port:
                  name: http